### PR TITLE
Tutorial7 akp

### PR DESCRIPTION
**Pull request by paulsonak**
updates based on kevin's feedback

### CODE REVIEW

**Comment by paulsonak** [comment]
@mauvais2 I'm not sure what the other commits (by you - last month) are or where they came from? I really only want to push the two that I created, [1078fa2](https://github.com/ATOMScience-org/AMPL/pull/322/commits/1078fa2df16c6f8dda5224a85f8e5ede16d70563) and [47062fb](https://github.com/ATOMScience-org/AMPL/pull/322/commits/47062fbea869b17b990a0f494becbb8e9f71fee2)

**Review by mcloughlin2 — APPROVED** [review]
It looks fine to me now.

**Comment by mauvais2** [comment]
It looks like at first you were based off dev_only branch. 

[dev_only](https://github.com/ATOMScience-org/AMPL/compare/dev_only)   -> [tutorial7_akp](https://github.com/ATOMScience-org/AMPL/compare/tutorial7_akp) ([#322](https://github.com/ATOMScience-org/AMPL/pull/322))

They look fine now.

**Comment by paulsonak** [comment]
made a new PR with only relevant changes

**Pull request closed without merging**
