### PR TITLE
Check for ECFP collisions

### PR DESCRIPTION
**Pull request by stewarthe6**
Sometimes different smiles result in the same ECFP features. Now you will receive a warning when that happens

### CODE REVIEW

**Review by paulsonak — COMMENTED** [review]
1. do you need to featurize the smiles or can you call this after the features have been calculated for the model/etc?
2. Might be worth adding a recommendation to the warning like, "we recommend trying a larger ECFP radius to reduce collisions"

**Review by mcloughlin2 — COMMENTED** [review]
I agree with Amanda, it would be helpful to suggest increasing the ECFP radius in the warning message. Otherwise the code looks fine.

**Comment by stewarthe6** [comment]
1. I think I already do? I have two functions. `check_ecfp_collisions` which featurizes smiles strings before calling `check_ecfp_feature_collisions` which does the actual check. I call `check_ecfp_feature_collisions` in `featurizer.py` after features have been calculated.
2. I updated the warning to suggest increasing `ecfp_radius`.

I have a followup question, do we need to escape literal SMILES strings when they have backslashes?

**Comment by paulsonak** [comment]
> do we need to escape literal SMILES strings when they have backslashes?

When would this need to happen? I think in general, no. In specific pandas operations (str.replace for instance) you can specify regex=False but I don't think any of that applies here. We would be getting errors and failures all the time if this was needed right?

**Comment by mcloughlin2** [comment]
When you specify a SMILES string as a string literal (e.g., 
smiles = "[O]/C(C1=CC=CC1)=C([S])\\N"), you should escape the backslashes; otherwise you may get a syntax error from Python complaining about a malformed escape sequence. If you’re reading the SMILES from a file, you don’t have to (and should not) escape them. The exception to the latter rule is if the SMILES string is going to be passed to some other piece of code (like a web app) that is going to interpret it as a string literal; then you have to double the backslashes. We have to do this when passing SMILES strings to the Allchemy REST API, for example.

**Review by paulsonak — APPROVED** [review]

**Pull request merged**
